name: signale
description: signale is a simple log package for dart with pure code, inspire from signale.js.
version: 0.0.12
homepage: https://github.com/nightmare-space/signale

environment:
  sdk: ">=2.12.0 <4.0.0"
