name: signale
description: Lightweight and easy to use printing tool.
version: 0.0.7
homepage: https://github.com/Nightmare-MY/signale

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

dev_dependencies:
